# Configuration for hyperparameter tuning pipelines

assets:
  - BTC-USDT
  - ETH-USDT

market_impact_params:
  alpha: [0.5, 1, 1.5]
  beta: [0.5, 1, 1.5]
  gamma: [0.01, 0.05, 0.1]
  eta: [0.01, 0.05, 0.1]
  risk_aversion: [0.0001, 0.001, 0.01]

slippage_params:
  quantiles: [0.5, 0.75, 0.9]

maker_taker_params:
  C_values: [0.01, 0.1, 1, 10]  # regularization strengths for LogisticRegression
